version: '2'
x-defaults: &app_template
  image: mlb-server:latest 
  networks:
    - shared

services:
  server-1:
    <<: *app_template
    environment:
      - NAME=1

  server-2:
    <<: *app_template
    environment:
      - NAME=2

  server-3:
    <<: *app_template
    environment:
      - NAME=3

  server-4:
    <<: *app_template
    environment:
      - NAME=4

  balancer:
    <<: *app_template
    image: mlb-balancer:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  shared:
    driver: bridge
